### ISSUE TITLE
0.4 release plans

### ISSUE THREAD

**Issue by kirbyfan64** [kirbyfan64/vuedart#15]
- [ ] ~~Proper test suite (#1; this needs to come first!).~~ nvm, this is getting delayed again.
- [x] Dart 2.0 support, primarily porting to `package:build` (#14).
- ~~[ ] Support for new VueMaterial and Vuetify.~~ Focus is instead going to [bindings for Google's official material components](https://github.com/kirbyfan64/vdmc).
- [x] Try to see if I can get some semblance of type-safety for events.
- [x] Mixin enhancements (#20).
- [ ] Update the docs.

Vuex support (#4) is going to get pushed back again...welp. :man_shrugging:

**Comment by dimiii** [comment]
BTW, when are you planning to ship this version?

**Comment by tjma2001** [comment]
https://github.com/kirbyfan64/vuedart/issues/21

**Comment by kirbyfan64** [comment]
@dimiii By the end of August.

**Comment by kirbyfan64** [comment]
It's been released!! :tada:

**Comment by tjma2001** [comment]
I want to throw you a party <3 :-) 

I am happy we have gotten to this point. Thank you for the hard work.
