### ISSUE TITLE
when will vuedart support Dart2？

### ISSUE THREAD

**Issue by zjuwjf** [kirbyfan64/vuedart#21]
Awesome project.
When will vuedart support Dart2？

**Comment by nevimjakou** [comment]
I agree. vuedart is a great project. I join with the same question.

**Comment by tjma2001** [comment]
from what I can see its almost there. Its just the documentation that needs to be updated; then the project should have the same equivalent state as v0.31.

**Comment by kirbyfan64** [comment]
Soon! The master branch works on Dart 2. 

Basically, the blockers right now before I can release 0.4 with Dart 2 support are:

- Updated docs.
- Trying to work around some really weird analyzer quirks with detecting mixins (this is my next target). 
- Probably throw in a few extra plugins as a bonus (this will probably take like 1 day, but it'd be nice to have it part of 0.4). 

It's definitely taken a bit longer to get this ready than I was anticipating, but I'm 99% sure it'll be released by the end of August. 

Thanks for your patience!

**Comment by zjuwjf** [comment]
Will 0.4 release at the end of August？ Or Will the plan be postponed for ...

**Comment by zjuwjf** [comment]
I really want to run the awesome project.

**Comment by kirbyfan64** [comment]
I had wiped my hard drive and had to recovery everything, so I'm now targeting September instead.
