### ISSUE TITLE
Dart 2

### ISSUE THREAD

**Issue by CrazyStaff** [kirbyfan64/vuedart#23]
When will be Dart 2 supported? Currently I cannot run vuedart 
in a browser with Dart version 2.0.0-dev.54.0 .

**Comment by kirbyfan64** [comment]
In 0.4, which should be released by the end of August. You can try the master branch if you want, but beware there's still a (very evasive) mixin bug I'm trying to catch.

**Comment by CrazyStaff** [comment]
The master branch has this restriction. Are you sure?

environment:
  sdk: ">=1.8.0 <2.0.0"

**Comment by kirbyfan64** [comment]
It has that restriction because the Dart team wasn't recommending that users update those constraints until rather recently (~1 month ago), and I haven't gotten around to updating it yet. 😉
