### ISSUE TITLE
Update analyzer dependency

### ISSUE THREAD

**Issue by bergwerf** [kirbyfan64/vuedart#34]
I'm getting complicated dependency issues because I import other packages that indirectly use the analyzer package (by including source_gen or build). E.g.:
```
Because source_gen >=0.9.4+1 depends on analyzer >=0.33.3 <0.36.0 and source_gen >=0.9.2 <=0.9.4 depends on analyzer >=0.33.0 <0.35.0, source_gen >=0.9.2 requires analyzer >=0.33.0 <0.36.0.
(1) So, because vue >=0.4.0 depends on analyzer ^0.32.2, vue >=0.4.0 is incompatible with source_gen >=0.9.2.
```
Long story short, I think this might be fixed if you upgrade some of your version constraints.

**Comment by bergwerf** [comment]
I now temporarily solved this by reducing the version lower bound on source_gen and analyzer in one of my indirect dependencies (I could do that because it is a small builder I developed). The analyzer and source_gen version jungle seems a bit tricky though, I am not sure what happens if you update your analyzer dependency bound though. We could also stall this issue until someone else encounters difficulties.

**Comment by kirbyfan64** [comment]
I might just have to set a bigger version bound on analyzer, this is the second time this has happened in like three months.
