### ISSUE TITLE
Update VueMaterial support

### ISSUE THREAD

**Issue by tobytraylor** [kirbyfan64/vuedart#39]
I realize that there are plans to have a direct dart wrapper around the Material Components implementation but in the short term would it be possible to update the legacy wrapper to the latest version of VueMaterial?  

I think people coming from flutter are looking to figure out what framework to use and the Material Components are extremely critical for that evaluation.

**Comment by refi64** [comment]
I do want to update it at some point, right now I'm just on a short term time crunch. That being said I did finish the major blocker that was preventing vdmc (the material components library) from having an actual release, so it should be out SOON(tm).

**Comment by tobytraylor** [comment]
Hey Ryan,
  Thanks for the quick response.  I'm also kinda on a time crunch to hit
demo and saw that you were able to build the docs site for the 0.4.0
release of vuedart with vdmc so i thought i'd give it a try, ran into a
dart 2x issue right off of the bat and cloned it to fix.  I'd love to help
as time permits and if i find issues i'll shoot you some PRs.  Thanks so
much for the great library in vuedart.  I spent the last 2 weeks in
angulardart and the components library was just driving me bat crazy.
Hopefully i can make up the time with the good stuff you have and get to
demo-able quikly.  Again, hoping to help out too.

**Comment by tobytraylor** [comment]
Wow.  The landscape for a good material components library for Vue is tough.  You've got the clear winner, vue-material, whose repo owner disappeared for like a half year and showed back up a few days ago.  You have material-components-vue whose owner is getting behind and is asking for help.  You have balmUI which is the new upstart, just a single guy who could give up at any moment since the project doesn't have much momentum.  And Vue MDC adapter, which has no commits since Aug of last year.  

How did you decide on material-compoents-vue?

**Comment by tobytraylor** [comment]
And there is https://github.com/posva/vue-mdc.  Which has been abandoned for over a year.  Jeez.  Need to convince these contributors to team up.

**Comment by tobytraylor** [comment]
And there is vue-material-adapter.  Wow.

**Comment by refi64** [comment]
Everything that I would've replied to here I put in the meta-issue #40, so closing.
