### ISSUE TITLE
vuedart create my-project gives "RangeError: Offset may not be negative, was -1"

### ISSUE THREAD

**Issue by h4xhor** [kirbyfan64/vuedart#44]
```
$ pub global activate vue_cli
$ vuedart create myproject
```

Note that using `vuedart create my-project` will fail at `pub get` with:
```
Error on line 1, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.
  ╷
1 │ name: my-project
  │       
```
... so I had to get rid of the hyphen (you may want to update the [official guide](https://refi64.com/vuedart/intro.html#welcome) .

Next running `$ webdev serve` will error with:
```
[SEVERE]vue:vue on web/index.dart: RangeError: Offset may not be negative, was -1.
```

This is strange as the same steps worked for me before and the directory that was previously working still works. Thanks.

**Comment by refi64** [comment]
#44
