### ISSUE TITLE
New to dart

### ISSUE THREAD

**Issue by imylomylo** [kirbyfan64/vuedart#9]
Hi,

I'm 0-day new to dart but am fond of vue.  Where's the best place to start looking at:

- How to use dart+vue with your package?

- How to look at this package and understand how it works to possibly contribute in the future?

Cheers

**Comment by kirbyfan64** [comment]
Welcome to the Dart world! :grin: 

If you're still learning Dart, the best way to start is the [official language tour](https://www.dartlang.org/guides/language/language-tour). Once you're done with that, [the VueDart documentation](https://refi64.com/vuedart/pages/intro.html) should be good enough to get you started.

I'm not quite sure what you mean by *How to look at this package and understand how it works to possibly contribute in the future?* though...

**Comment by imylomylo** [comment]
OK thanks for pointers.

"how to look at this package....." - ignore that superfluous comment i guess :)  basically just to understand dart package / js integration.  The fellow from the dart package called 'vue' suggested to look at the js integration package to understand how dart/js integration works.  As an aside, his project has been abandoned - in case you wanted to rename your package vue, he's willing to give it up.  (https://github.com/emilniklas/vue-dart/issues/2 first response)

**Comment by kirbyfan64** [comment]
@imylomylo Thanks for the heads up! I touch on JS integration in the docs [here](https://refi64.com/vuedart/pages/advanced.html#boundary) with some links to the `package:js` documentation.
